name: Gatsby Publish

on:
  push:
    branches:
      - githubaction

env:
  STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
  STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
  GATSBY_UPDATE_SCHEMA_SNAPSHOT: ${{ secrets.GATSBY_UPDATE_SCHEMA_SNAPSHOT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          working-dir: src/app
