name: Gatsby Publish

on:
  push:
    branches:
      - githubaction

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
      STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
      GATSBY_UPDATE_SCHEMA_SNAPSHOT: ${{ secrets.GATSBY_UPDATE_SCHEMA_SNAPSHOT }}
    steps:
      - uses: actions/checkout@v1
      
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          working-dir: src/app
